### ISSUE TITLE
sqlite3.OperationalError: no such table: last_downloads

### ISSUE THREAD

**Issue by Mirabis** [Donny87/autosub-bootstrapbill#140]
```upgradeDb: Upgrading database  from version 1 to version 7
upgradeDb: 6 upgrades are required. Starting subupgrades
upgradeDb: Upgrading database  from version 1 to version 2
Traceback (most recent call last):
  File "/opt/AutoSub/AutoSub.py", line 126, in <module>
    sys.exit(main())
  File "/opt/AutoSub/AutoSub.py", line 103, in main
    autosub.Db.initDatabase()
  File "/opt/AutoSub/autosub/Db.py", line 252, in initDatabase
    upgradeDb(autosub.DBVERSION, version.dbversion)
  File "/opt/AutoSub/autosub/Db.py", line 168, in upgradeDb
    upgradeDb(from_version + x, from_version + x + 1)
  File "/opt/AutoSub/autosub/Db.py", line 175, in upgradeDb
    cursor.execute("ALTER TABLE last_downloads ADD COLUMN '%s' 'TEXT'" % 'codec')```

**Comment by Mirabis** [comment]
My mistake.. sorry - was using the old source.. just updated = fixed.
