### ISSUE TITLE
Crash in Helpers.py

### ISSUE THREAD

**Issue by idserda** [Donny87/autosub-bootstrapbill#149]
Linux, Python 2.7.6, commit `350341343f6fbd393e8de88158ccbf90c23a7f67`

```
Traceback (most recent call last):
  File "/home/jeroen/Applications/autosub-bootstrapbill/autosub/Scheduler.py", line 21, in __init__
    self.command.run()
  File "/home/jeroen/Applications/autosub-bootstrapbill/autosub/checkSub.py", line 90, in run
    showid,a7_id, OsId = Helpers.getShowid(title, UseAddic, UseOpensubtitles)
  File "/home/jeroen/Applications/autosub-bootstrapbill/autosub/Helpers.py", line 351, in getShowid
    AddicId = AddicIdMapping    if AddicIdMapping    else AddicId
UnboundLocalError: local variable 'AddicIdMapping' referenced before assignment
```

**Comment by Donny87** [comment]
Let me know if the new commit fixed it for you.

**Comment by idserda** [comment]
Works fine now, thanks.
